# Generated by Django 5.1 on 2024-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='usern',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
