# Generated by Django 5.1 on 2024-08-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userscore_usern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
    ]
