# Generated by Django 5.1 on 2024-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='animals',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='computer',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='gk',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='science',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='sports',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
