# Generated by Django 5.1 on 2024-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userscore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='gk',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
    ]
