# Generated by Django 5.1 on 2024-08-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='gk',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
