# Generated by Django 5.1 on 2024-08-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_animals_computer_science_sports_alter_gk_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
    ]
