# Generated by Django 5.1 on 2024-08-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_animals_animal_rename_sports_sport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
