# Generated by Django 5.1 on 2024-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('correct', models.CharField(max_length=400)),
                ('incorrect1', models.CharField(max_length=400)),
                ('incorrect2', models.CharField(max_length=400)),
                ('incorrect3', models.CharField(max_length=400)),
            ],
        ),
    ]
